### ISSUE TITLE
Proposal: `--prerelease` flag

### ISSUE THREAD

**Issue by Emik03** [dotnet-campus/dotnetCampus.UpdateAllDotNetTools#14]
I would find it very useful to run `dotnet-updatealltools --prerelease` which would add `--prerelease` as an additional argument for every process, making this tool very useful to keep yourself up-to-date with nightly/weekly builds.

**Comment by lindexi** [comment]
@Emik03 Could you try the 1.0.9 version

**Comment by Emik03** [comment]
Works great, thank you!

**Comment by lindexi** [comment]
Thank you @Emik03
