### ISSUE TITLE
Unhandled exception on Mac

### ISSUE THREAD

**Issue by panosru** [dotnet-campus/dotnetCampus.UpdateAllDotNetTools#4]
Hello! Nice tool! I tried to use it but I'm getting the following exception:

![image](https://user-images.githubusercontent.com/400362/89236212-9fedf800-d5f8-11ea-9ddf-92835f8cea61.png)

and obviously, as I can see from the exception `System.ComponentModel.Win32Exception` that is a normal exception since I'm not on a windows 32 platform :)

**Comment by lindexi** [comment]
@panosru Can you try the latest version of the tool?

**Comment by panosru** [comment]
@lindexi hey! Thanks for the update! It seems to work but I got a Win32Exception at the end:

![image](https://user-images.githubusercontent.com/400362/89737440-aefdfb80-da79-11ea-8a83-eb1abff4e1d6.png)

**Comment by lindexi** [comment]
@panosru Thank you and we add some log. Could you update the tool and test it?

**Comment by panosru** [comment]
@lindexi Good day! Sure! This is the output I'm getting now:

![image](https://user-images.githubusercontent.com/400362/89867672-2e92e400-dbba-11ea-9d79-aef83dc1fcb3.png)

**Comment by lindexi** [comment]
@panosru  Thank you. But I do not know why.

It seems that can not find the `dotnet` file to run.

**Comment by lindexi** [comment]
@panosru Could you create a console application and run this code?

            var fileName = "dotnet";
            var argument = "tool updatelivereloadserver -g";
            var process = new Process
            {
                StartInfo =
                {
                    FileName = fileName,
                    Arguments = argument,
                    WorkingDirectory = workingDirectory,
                    UseShellExecute = false, 
                    RedirectStandardOutput = true, 
                    RedirectStandardError = true, 
                    CreateNoWindow = true, 
                }
            };

            process.Start(); // Maybe throw win32 exception

**Comment by panosru** [comment]
@lindexi it worked fine:

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var fileName = "dotnet";
            var argument = "tool update livereloadserver -g";
            var workingDirectory = Environment.CurrentDirectory;
            var process = new Process
            {
                StartInfo =
                {
                    FileName = fileName,
                    Arguments = argument,
                    WorkingDirectory = workingDirectory,
                    UseShellExecute = false, 
                    RedirectStandardOutput = true, 
                    RedirectStandardError = true, 
                    CreateNoWindow = true, 
                }
            };
            
            process.Start(); // Maybe throw win32 exception
            string result = process.StandardOutput.ReadToEnd();
            process.WaitForExit();
            Console.WriteLine(result);
        }
    }
```

![image](https://user-images.githubusercontent.com/400362/89870814-15d8fd00-dbbf-11ea-8b1c-a3530c698762.png)

**Comment by lindexi** [comment]
@panosru Thank you. But I do not know why.

**Comment by panosru** [comment]
@lindexi it's strange because if I clone the project and run `dotnet run`, it works fine:

![image](https://user-images.githubusercontent.com/400362/89885386-a6213d00-dbd3-11ea-8938-0445ab377be7.png)

**Comment by kkwpsv** [comment]
I have also tested it on my macOS and it works fine.
It's so strange.....

**Comment by panosru** [comment]
yes, it is indeed, if I install the tool via `dotnet tool install` then I'm getting the error I showed you (do you also get the same error?), if I run the `Program.cs` with `dotnet run` it then works fine... strange.

**Comment by kkwpsv** [comment]
The real reason is that our executable file has been updated and failed when try to get executable file by pid.

**Comment by lindexi** [comment]
@panosru Could you try the latest version?

**Comment by panosru** [comment]
@lindexi sorry for the late response! I tried the latest version, still getting at the end the same exception:

![image](https://user-images.githubusercontent.com/400362/90248480-72e3e580-de41-11ea-80ce-9af8abae9f0e.png)

removing livereloadserver plugin didn't help:

![image](https://user-images.githubusercontent.com/400362/90248563-9b6bdf80-de41-11ea-98dc-4862fdb85d95.png)

even when I remove all plugins, it still throws Win32Exception when it tries to run `dotnet tool update dotnetCampus.UpdateAllDotNetTools -g`

**Comment by lindexi** [comment]
@panosru Thank you. I know why and I will fix it.

**Comment by lindexi** [comment]
@panosru Could you try the latest version?

**Comment by panosru** [comment]
@lindexi now it works like a charm! Thanks ;)

![image](https://user-images.githubusercontent.com/400362/90257611-14723380-de50-11ea-8ab6-9886c30b2a14.png)

**Comment by lindexi** [comment]
@panosru Thank you.
